export const Locale = {
  // products
  product_information: "Product Information",
  product_details: "Product Details",
  product_image_and_video: "Product Image and Video",
  video: "Videos",
  youtube_link: "Youtube Link",
  stories: "Stories",
  show: "Show",
  video_url: "Video Url",
  add_story: "Add Story",
  edit_story: "Edit Story",
  languages_localisation: "Languages Localisation",
  languages: "Languages",
  default_language: "Default Language",
  local: "Local",
  // branches
  branch_info: "Branch Info",
  images_and_videos: "Images and videos",
  tag_product: "Tag Product",
  dashboard: "Dashboard",
  branches: "Branches",
  branch_text:
    "Create new branches, add or edit your categories, subCategories and inventory.",
  add_branch: "Add Branch",
  branch_name: "Branch Name",
  edit_branch: "Edit Branch",
  orders: "Orders",
  order_text: "Design your menu to reflect your business and your brand.",
  products: "Products",
  areas_text: "List of Areas.",
  product_name: "Product Name",
  select_a_product: "Select A Product",
  add_product: "Add Product",
  edit_product: "Edit Product",
  sub_category: "Sub Category",
  add_category: "Add Category",
  add_new_category: "Add New Category",
  add_share_category: "Add Share Category",
  category_icon: "Category Icon",
  category_name: "Category Name",
  edit_category: "Edit Category",
  categories: "Categories",
  add_sub_Category: "Add Sub-Category",
  sub_category_name: "Sub Category Name",
  edit_sub_category: "Edit Sub-Category",
  select_subCategory: "Select SubCategory",
  companies: "Companies",
  company: "Company",
  add_company: "Add Company",
  user_id: "User ID",
  company_name: "Company Name",
  edit_company: "Edit Company",
  inventory: "Inventory",
  variants: "Variants",
  add_variant: "Add Variant",
  add_to_inventory: "Add To Inventory",
  variant_name: "Variant Name",
  buying_quantity: "Buying Quantity",
  buying_price: "Buying Price",
  selling_price: "Selling Price",
  selling_quantity: "Selling Quantity",
  description: "Description",
  advice: "Advice",
  current_price: "Current Price",
  old_price: "Old Price",
  images: "Images",
  edit_inventory: "Edit Inventory",
  variant_quantity: "Variant Quantity",
  variant_details: "Variant Details",
  variant_list: "Variant List",
  edit_variant: "Edit Variant",
  add_details: "Add Details",
  attributes_add_note:
    "Click here to add your option if it isn't already there. : ",
  actions: "Actions",
  number: "#NO",
  id: "ID",
  profile: "Profile",
  close: "Close",
  save: "Save",
  services_areas: "Services-Areas",
  services_area: "Services Area",
  add_service_area: "Add Service Area",
  edit_service_area: "Edit Service Area",
  service_area: "Service Area",
  units: "Units",
  select_a_option: "Select A Option",
  add_unit: "Add Unit",
  unit_name: "Unit Name",
  edit_unit: "Edit Unit",
  unit: "Unit",
  gallery: "Gallery",
  add_to_gallery: "Add To Gallery",
  logout: "Logout",
  edit: "Edit",
  delete: "Delete",
  update: "Update",
  loading: "Loading...!",
  completed: "Completed",
  status: "Status",
  welcome_msg: "Hi, welcome !",
  minus: " - ",
  plus: " + ",
  availability: "Availability",
  variant_code: "Variant Code",
  email: "E-mail",
  email_msg: "Enter Your Email/Phone Number",
  password: "Password",
  password_msg: "Enter Your Password",
  full_name: "Full Name",
  phone: "Phone",
  already_have_an_account: "Already have an account?",
  cancel: "Cancel",
  confirm: "Confirm",
  currency: "Currency",
  select_currency: "Select Currency",
  not_available: "Sorry, more then that is not available in stock.",
  sub_category_icon: "Sub Category Icon",
  display_mobile: "Display Mobile",
  home: "Hello Menu",
  preview: "Preview",
  number_of_related_products: "Number of related products:",
  add_variant_details: "Add Variant Details",
  public_link: "Public Link",
  details: "Details",
  value: "Value",
  name: "Name",
  edit_variant_detail: "Edit Variant Detail",
  hello_menu: "Hello Menu",
  tables: "Tables",
  add_table: "Add Table",
  table_number: "Table Number",
  table_name: "Table Name",
  edit_table: "Edit Table",
  download_qr_code: "Download QR Code",
  qr_code: "QR Code",
  areas: "Areas",
  add_area: "Add Area",
  name_area: "Area Name",
  add: "Add New",
  order_now_by_whatsapp: "Order Now By WhatsApp",
  delivery_fees: "Delivery Fees",
  grand_total: "Grand Total",
  note: "Note",
  phone_number: "Phone Number",
  general_note: "General Note",
  send_order: "Send Order",
  clear_basket: "Clear Basket",
  order_id: "Order ID",
  address: "Address",
  buildingNo: "Building No",
  floor: "Floor",
  flat: "Flat",
  directions: "Directions",
  attributes: "Attributes",
  attribute_name: "Attribute Name",
  add_attribute: "Add Attribute",
  edit_Attribute: "Edit Attribute",
  products_list: "Products List",
  select_a_attributes: "Select Attributes",
  option_name: "Option Name",
  add_option: "Add Option",
  options: "Options",
  edit_option: "Edit Option",
  download: "Download",
  attribute_variant_details: "Attributes Variant Details",
  image: "Image",
  product_variation: "Product Variation",
  add_variants: "Add Variants",
  quantity: "Quantity",
  price: "Price",
  vatiants: "Vatiants",
  design: "Design",
  screen_orientation: "Screen Orientation",
  menu_structure: "Menu Structure",
  logo: "Logo",
  new_theme: "New Theme",
  themes: "Themes",
  landscape: "Landscape",
  portrait: "Portrait",
  infinite_scroll: "Infinite Scroll",
  classic_layout: "Classic Layout",
  note_for_logo: "The logo will be shown on Menu Screen only.",
  tablet_menu: "Tablet Menu",
  QR_code: "QR-Code",
  text_color: "Text Color",
  highlight_color: "Highlight Color",
  bgColor: "Root Background Color",
  cardBgColor: "Card Background Color",
  menusAcriveColor: "Menus Acrive Color",
  menusDeactiveColor: "Menus Deactive Color",
  menusSize: "Menus Font Size",
  card_color: "Card Color",
  home_screen_background: "Home Screen Background",
  // menu_screen_background: "Menu Screen Background",
  theme_colors: "Theme Colors",
  menu_button: "Menu Button",
  solid_color: "Solid Color",
  image_or_video: "Image / Video",
  show_button: "Show Button",
  button_shape: "Button Shape",
  round: "Round",
  pill: "Pill",
  advanced_customization: "Advanced Customization(Coming Soon)",
  customization: "Customization",
  selected: "Selected",
  your_helloMenu_QR: "Your Hello Menu QR",
  QR_code_color: "QR Code Color",
  QR_code_background_color: "QR Code Background Color",
  theme_name: "ThemeName",
  duplicate: "Duplicate",
  sub_categories: "Sub Categories",
  public_categories: "Categories",
  product_variants: "Product Variants",
  custom_design: "Custom Design",
  default_templates: "Default Templates",
  default: "Default",
  branch_name_color: "Branch Name Color",
  branch_name_font_size: "Branch Name Font Size",
  categories_and_sub_categoies_color: "Categories/Sub Categoies Color",
  categories_and_sub_categoies_font_size: "Categories/Sub Categoies Font size",
  product_name_color: "Product Name Color",
  pNameSize: "Product Name Font Size",
  product_discription_color: "Product Discription Color",
  pDiscriptionSize: "Product Discription Font Size",
  price_color: "Price Color",
  priceSize: "Price Font Size",
  button_text_color: "Button Text Color",
  button_background_color: "Button Background Color",
  bTextSize: "Button Text Font Size",
  show_extras: "Show Extras",
  show_ingredients: "Show Ingredients",
  show_recommendation: "Show Recommendation",
  show_variants: "Show Variants",
  number_of_products_in_each_row: "Number of Products in Each Row",
  mode: "Mode",
  font: "Font",
  back: "Back",
  reset_to_default: "Reset to Default",
  sku: "SKU",
  stock: "Stock",
  back_to_products_list: "Back to Products List",
  ingredients: "Ingredients",
  add_ingredient: "Add Ingredient",
  edit_ingredient: "Edit Ingredient",
  preparation_Time: "Preparation Time",
  extras: "Extras",
  add_extra: "Add Extra",
  edit_extra: "Edit Extra",
  recommendation_products: "Recommendation Products",
  show_preparation_time: "Display Preparation Time",
  recommendation: "Recommendation",
  save_and_preview: "Save & Preview",
  empty_cart: "Empty Cart",
  remove_all: "Remove All",
  share_product_with_other_branches: "Share Product With Other Branches",
  share_category_with_other_branches: "Share Category With Other Branches",
  cityName: "City Name",
  city: "City",
  back_to_categories: "Back to Categories",
  share_with: "Share With",
  ordering_methods: "Ordering Methods",
  order_details: "Order Details",
  ordering_phone_number: "Ordering Phone Number",
  number_of_seats: "Number of seats",
  download_all: "Download All",
  addressing_method: "Addressing Method",
  add_more: "Add More",
  qrcode_style: "QRCode-Style",
  settings: "Settings",
  settings_management: "Settings Management",
  company_discription: "Company Discription",
  facebook: "Facebook",
  instagram: "Instagram",
  youtube: "Youtube",
  tiktok: "Tiktok",
  whatsapp: "WhatsApp",
  social_links: "SOCIAL LINKS",
  contact_email: "Contact Email",
  business_type: "Business Type",
  submit: "Submit",
  change: "Change",
  edit_profile: "Edit Profile",
  confirm_new_password: "Confirm New Password",
  new_password: "New Password",
  current_password: "Current Password",
  close_account: "Close Account",
  total: "Total",
  rows: "Rows",
  areaName: "Area Name",
  noItemFound: "No Item Found",
  dateAndTime: "Date and Time",
};
