export const PublicLocale = {
  loading: "Loading...",
  yay_you_have_seen_it_all: "Yay! You have seen it all",
  stories: "Stories",
  list_of_videoes: "List of Videoes",
  no_data_found: "No Data Found",
  more_than_that_isnot_available_because_itis_out_of_stock:
    "More than that isn't available because it's out of stock.",
  please_select_product_variantion: "Please select product variantion",
  see_more: "See More",
  add_to_cart: "Add to Cart",
  add_to_wishlist: "Add to WishList",
  preparation_time: "Preparation Time",
  price: "Price",
  stock: "Stock",
  variants: "variants",
  item_variant: "Item Variant",
  ingredients: "Ingredients",
  extras: "Extras",
  recommendation: "Recommendation",
  search_by_name: "Search By Name",
  all: "All",
  sub_total: "Sub Total",
  delivery_fee: "Delivery Fee",
  order_details: "Order Details",
  cart: "Cart",
  table_number: "Table Reservation",
  reservation_date_and_time: "Reservation Date and Time",
  discard_reason: "Discard Reason",
  table_reservation: "Table Reservation",
  reserve_a_table: "Reserve a table",
  home_delivery: "Home Delivery",
  whatsApp: "WhatsApp",
  no_item_available: "No Item Available",
  ordering_methods: "Ordering Methods",
  scan_QR_code: "Scan QR Code",
  successfully_authenticated: "successfully authenticated",
  select_a_table: "Select a Table",
  seater: "Seater",
  full_address: "Full Address",
  general_note: "General Note",
  send_order: "Send Order",
  empty_cart: "Empty Cart",
  // checkout_order: "Checkout Order",
  date_and_time: "Date and Time",
  grand_total: "Grand Total",
  total_price: "Total Price",
  item_note: "Item Note",
  qty: "Qty",
  unit_name: "Unit Name",
  product_name: "Product Name",
  category: "Category",
  sub_category: "Sub Category",
  item_total_price: "Item Total Price",
  address: "Address",
  checkout: "Checkout",
  minutes: "Minutes",
  please_choose_at_least_one_way_of_ordering:
    "Please choose at least one way of ordering.",
  please_scan_the_table_QR_code: "Please Scan The Table QR-Code",
  please_select_table_reservation: "Please Select Table Reservation",
  successfully_added: "Successfully added",
  updated: "Updated",
  please_select_the_ingredients_you_want_to_remove:
    "Please select the ingredients you want to remove.",
  item_is_already_in_cart: "Item is Already in cart",
  close: "Close",
  profile: "Profile",
  home: "Home",
  track_order: "Track Order",
};
